Factory.define :idea do |i|
  i.title  "Factory Idea"
  i.description  "Let's build object from factories'"
  i.user_id  1
  i.like  2
  i.dislike  1
  i.association :users, :factory => :users
end

Factory.define :users do |u|
  u.name  "Factory Girl"
  u.about  "I am generated by a factories."
  u.email "girl@factory.com"
  u.password "password"
end